apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: {{ .Values.gateway.label }} # use istio default controller
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: {{ .Values.gateway.serverName }}
      protocol: {{ .Values.gateway.protocol }}
    hosts:
    - "*"