apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 3
      memory: 2Gi
    defaultRequest: # this section defines default requests
      cpu: 3
      memory: 2Gi
    max: # max and min define the limit range
      cpu: 4
      memory: 3Gi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container
