apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.role.name }}
rules:
 - apiGroups: [""]
   resources: ["configmaps", "secrets"]
   verbs: ["get", "list", "watch"]
 - apiGroups: ["crwebapp.my.domain"]
   resources: ["webappcrs"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]