apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
   - route:
      - destination:
          host: {{ .Release.Name }}-service.webapp.svc.cluster.local
          port:
            number: {{ .Values.gateway.port }}